MAIN=connector_what_we_sell
OUTPUT=CONNECTOR_WHAT_WE_SELL.pdf

.PHONY: all clean view

all: $(OUTPUT)

$(OUTPUT): $(MAIN).tex
	pdflatex -interaction=nonstopmode $(MAIN).tex
	pdflatex -interaction=nonstopmode $(MAIN).tex
	mv -f $(MAIN).pdf $(OUTPUT)

clean:
	rm -f $(MAIN).aux $(MAIN).log $(MAIN).out $(MAIN).toc $(MAIN).pdf $(OUTPUT)

view: $(OUTPUT)
	xdg-open $(OUTPUT) 2>/dev/null || open $(OUTPUT) 2>/dev/null || echo "Open $(OUTPUT) manually"
