#!/usr/bin/env bash
# Print manual Cloudflare DNS steps when API token is IP-restricted (9109).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${CONNECTOR_DEPLOY_ENV:-$ROOT/.env}"
[[ -f "$ENV_FILE" ]] && { set -a; source "$ENV_FILE"; set +a; }

LICENSE_HOST="${LICENSE_FLY_HOST:-connector-license.fly.dev}"
PLAYGROUND_HOST="${PLAYGROUND_FLY_HOST:-connector-playground.fly.dev}"

echo "══════════════════════════════════════════════════════════════"
echo " Cloudflare DNS — manual fix (525 / orange-cloud / Fly certs)"
echo "══════════════════════════════════════════════════════════════"
echo ""
echo "Your API token is blocked from this machine (error 9109 — IP filter)."
echo "Fix token OR set records in dashboard: dash.cloudflare.com → cnktros.com → DNS"
echo ""
echo "Add/update these CNAME records with PROXY STATUS = DNS only (gray cloud):"
echo ""
printf "  %-8s  %-35s  %s\n" "NAME" "TARGET" "PROXY"
printf "  %-8s  %-35s  %s\n" "----" "------" "-----"
printf "  %-8s  %-35s  %s\n" "api" "$LICENSE_HOST" "DNS only"
printf "  %-8s  %-35s  %s\n" "portal" "$LICENSE_HOST" "DNS only"
printf "  %-8s  %-35s  %s\n" "admin" "$LICENSE_HOST" "DNS only"
printf "  %-8s  %-35s  %s\n" "try" "$PLAYGROUND_HOST" "DNS only"
echo ""
echo "Optional (marketing on Vercel):"
echo "  @ or www → cname.vercel-dns.com (proxied OK)"
echo ""
echo "After DNS propagates (~2–5 min):"
echo "  fly certs check api.cnktros.com -a connector-license"
echo "  fly certs check portal.cnktros.com -a connector-license"
echo "  fly certs add admin.cnktros.com -a connector-license   # if missing"
echo "  fly certs check try.cnktros.com -a connector-playground"
echo ""
echo "Test:"
echo "  curl https://api.cnktros.com/health"
echo "  curl https://portal.cnktros.com/"
echo "  curl https://admin.cnktros.com/admin"
echo "  curl https://try.cnktros.com/health"
echo ""
echo "To fix API token for scripts (optional):"
echo "  Cloudflare → My Profile → API Tokens → edit token"
echo "  Remove IP Address Filtering, OR add:"
ipv4="$(curl -4 -sS --max-time 5 ifconfig.me 2>/dev/null || true)"
ipv6="$(curl -6 -sS --max-time 5 ifconfig.me 2>/dev/null || true)"
[[ -n "$ipv4" ]] && echo "    IPv4: $ipv4"
[[ -n "$ipv6" ]] && echo "    IPv6: $ipv6"
echo ""
echo "Then run one record at a time:"
echo "  DNS_RECORD=api bash platform/deploy/scripts/cloudflare-dns.sh"
echo "══════════════════════════════════════════════════════════════"
