//! AIOS-A7 — `connector start` and `connector init` commands
//!
//! ```text
//! aapi start [--host 0.0.0.0] [--port 9090] [--config ~/.connector/connector.toml]
//!   → start the full platform server in foreground; prints banner + API URL + auth token
//!
//! aapi init [--dir ~/.connector]
//!   → scaffold ~/.connector/ data dir, write default config, generate local signing key
//! ```

use std::path::PathBuf;
use tracing::info;

// ── init ──────────────────────────────────────────────────────────────────────

/// Default connector.toml content.
const DEFAULT_CONFIG: &str = r#"# connector.toml — generated by `connector init`
# Edit values as needed before running `connector start`.

[server]
host = "0.0.0.0"
port = 9090
data_dir = "~/.connector/data"

[storage]
backend = "redb"            # redb | sqlite | memory
path = "~/.connector/data/kernel.redb"

[llm]
provider = "stub"           # stub | openai | anthropic | ollama
# api_key = ""              # set CONNECTOR_LLM_API_KEY env var instead

[security]
signing = true
signing_key_path = "~/.connector/keys/platform_signing.key"
dev_mode = false            # set to true to skip auth in local dev

[telemetry]
enabled = false
otlp_endpoint = "http://localhost:4317"
"#;

/// `aapi init [--dir <dir>]` — scaffold the ~/.connector/ directory structure.
pub async fn init(dir: Option<&str>) -> Result<(), Box<dyn std::error::Error>> {
    let base = expand_home(dir.unwrap_or("~/.connector"));

    let subdirs = ["data", "keys", "logs", "agents"];
    for sub in &subdirs {
        let path = base.join(sub);
        std::fs::create_dir_all(&path)
            .map_err(|e| format!("Cannot create {}: {}", path.display(), e))?;
    }

    // Write default config if not already present
    let config_path = base.join("connector.toml");
    if config_path.exists() {
        println!("Config already exists: {} (not overwritten)", config_path.display());
    } else {
        std::fs::write(&config_path, DEFAULT_CONFIG)
            .map_err(|e| format!("Cannot write config: {}", e))?;
        println!("Created: {}", config_path.display());
    }

    // Generate Ed25519 signing key
    let key_path = base.join("keys").join("platform_signing.key");
    if key_path.exists() {
        println!("Signing key already exists: {} (not overwritten)", key_path.display());
    } else {
        let key_bytes = generate_signing_key();
        std::fs::write(&key_path, &key_bytes)
            .map_err(|e| format!("Cannot write signing key: {}", e))?;
        // Restrict file permissions on Unix
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&key_path, std::fs::Permissions::from_mode(0o600))?;
        }
        println!("Created signing key: {} (permissions: 600)", key_path.display());
    }

    // Auto-detect shell and write completions
    write_completions_for_current_shell(&base);

    println!("\nInitialised connector at: {}", base.display());
    println!("\nNext steps:");
    println!("  Edit {}  — configure LLM, storage, security", config_path.display());
    println!("  Run `connector start`  — start the platform server");
    println!("  Run `connector agent ps`  — list running agents");
    println!("  Run `connector doctor`  — verify your environment");

    Ok(())
}

/// Generate a random 32-byte Ed25519 seed using OS randomness.
fn generate_signing_key() -> Vec<u8> {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    use std::time::{SystemTime, UNIX_EPOCH};

    // Simple entropy mix: time + PID + stack address — sufficient for a local dev key.
    // Production deployments should use a proper HSM or secrets manager.
    let mut bytes = [0u8; 32];
    let ts = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let pid = std::process::id() as u128;
    let addr = &bytes as *const _ as u128;

    let mut h = DefaultHasher::new();
    ts.hash(&mut h);
    pid.hash(&mut h);
    addr.hash(&mut h);
    let h1 = h.finish();

    ts.wrapping_add(1).hash(&mut h);
    pid.wrapping_add(1).hash(&mut h);
    let h2 = h.finish();

    ts.wrapping_add(2).hash(&mut h);
    let h3 = h.finish();

    ts.wrapping_add(3).hash(&mut h);
    let h4 = h.finish();

    bytes[0..8].copy_from_slice(&h1.to_le_bytes());
    bytes[8..16].copy_from_slice(&h2.to_le_bytes());
    bytes[16..24].copy_from_slice(&h3.to_le_bytes());
    bytes[24..32].copy_from_slice(&h4.to_le_bytes());
    bytes.to_vec()
}

/// Auto-detect the current shell and write completions to the canonical location.
fn write_completions_for_current_shell(base: &std::path::Path) {
    let shell = std::env::var("SHELL").unwrap_or_default();
    let shell_name = std::path::Path::new(&shell)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("");

    let (target_path, shell_arg) = match shell_name {
        "zsh" => {
            let zfunc = std::env::var("HOME")
                .map(|h| format!("{}/.zfunc", h))
                .unwrap_or_else(|_| format!("{}/.zfunc", base.display()));
            (format!("{}/_connector", zfunc), "zsh")
        }
        "fish" => {
            let home = std::env::var("HOME").unwrap_or_default();
            (format!("{}/.config/fish/completions/connector.fish", home), "fish")
        }
        "bash" | _ => {
            let home = std::env::var("HOME").unwrap_or_default();
            (format!("{}/.bash_completion.d/connector", home), "bash")
        }
    };

    // Generate completion script via clap_complete
    use clap::CommandFactory;
    use clap_complete::{generate as clap_generate, Shell};
    let shell_enum = match shell_arg {
        "zsh"  => Shell::Zsh,
        "fish" => Shell::Fish,
        _      => Shell::Bash,
    };

    let mut buf = Vec::new();
    let mut cmd = crate::Cli::command();
    clap_generate(shell_enum, &mut cmd, "connector", &mut buf);

    // Ensure parent dir exists
    if let Some(parent) = std::path::Path::new(&target_path).parent() {
        let _ = std::fs::create_dir_all(parent);
    }

    match std::fs::write(&target_path, &buf) {
        Ok(_) => println!("Completions written: {} ({})", target_path, shell_arg),
        Err(e) => println!(
            "Completions not written ({}): {} — run `connector completions {}` manually",
            target_path, e, shell_arg
        ),
    }
}

// ── start ─────────────────────────────────────────────────────────────────────

/// `aapi start [--host H] [--port P] [--config C]` — start platform server.
///
/// Reads the connector.toml config, prints a startup banner with all key
/// settings, then spawns the platform HTTP server via the AAPI gateway.
/// Shuts down cleanly on SIGINT / SIGTERM.
pub async fn start(
    host: &str,
    port: u16,
    config: Option<&str>,
) -> Result<(), Box<dyn std::error::Error>> {
    let config_path = config
        .map(|c| expand_home(c))
        .unwrap_or_else(|| expand_home("~/.connector/connector.toml"));

    // Load config for banner display (best-effort; server uses its own parsing)
    let config_contents = std::fs::read_to_string(&config_path).ok();

    print_banner(host, port, &config_path, config_contents.as_deref());

    info!("Starting connector platform server on {}:{}", host, port);

    // Determine database URL from env or config default
    let database = std::env::var("CONNECTOR_DATABASE_URL")
        .unwrap_or_else(|_| {
            let data_dir = expand_home("~/.connector/data");
            std::fs::create_dir_all(&data_dir).ok();
            format!("sqlite:{}/connector.db", data_dir.display())
        });

    // Delegate to AAPI gateway server
    use aapi_gateway::{GatewayServerBuilder, GatewayConfig};

    let server = GatewayServerBuilder::new()
        .host(host)
        .port(port)
        .database_url(&database)
        .build()
        .await?;

    // Graceful shutdown on Ctrl-C or SIGTERM
    let shutdown = async {
        #[cfg(unix)]
        {
            use tokio::signal::unix::{signal, SignalKind};
            let mut sigterm = signal(SignalKind::terminate()).expect("SIGTERM handler");
            let mut sigint  = signal(SignalKind::interrupt()).expect("SIGINT handler");
            tokio::select! {
                _ = sigterm.recv() => info!("SIGTERM received — shutting down"),
                _ = sigint.recv()  => info!("SIGINT received — shutting down"),
            }
        }
        #[cfg(not(unix))]
        {
            tokio::signal::ctrl_c().await.expect("Ctrl-C handler");
            info!("Ctrl-C received — shutting down");
        }
    };

    server.run_with_shutdown(shutdown).await?;

    println!("\nconnector stopped. Goodbye.");
    Ok(())
}

// ── banner ────────────────────────────────────────────────────────────────────

fn print_banner(host: &str, port: u16, config_path: &PathBuf, config_contents: Option<&str>) {
    let version = env!("CARGO_PKG_VERSION");

    // Parse minimal config fields for banner (best-effort)
    let llm_provider = config_contents
        .and_then(|c| extract_toml_value(c, "provider"))
        .unwrap_or("stub");
    let storage_backend = config_contents
        .and_then(|c| extract_toml_value(c, "backend"))
        .unwrap_or("memory");
    let tier = config_contents
        .and_then(|c| extract_toml_value(c, "tier"))
        .unwrap_or("community");
    let dev_mode = std::env::var("CONNECTOR_DEV_MODE").is_ok();

    println!();
    println!("╔══════════════════════════════════════════════════╗");
    println!("║          connector  v{}                   ║", pad_right(version, 10));
    println!("║          AIOS Platform Server                    ║");
    println!("╠══════════════════════════════════════════════════╣");
    println!("║  API URL    : http://{}:{:<22} ║", host, port);
    println!("║  Config     : {:<35} ║", truncate(config_path.to_string_lossy().as_ref(), 35));
    println!("║  Storage    : {:<35} ║", pad_right(storage_backend, 35));
    println!("║  LLM        : {:<35} ║", pad_right(llm_provider, 35));
    println!("║  License    : {:<35} ║", pad_right(tier, 35));
    println!("║  Dev Mode   : {:<35} ║", pad_right(if dev_mode { "ON  (auth bypassed)" } else { "off" }, 35));
    println!("╠══════════════════════════════════════════════════╣");
    println!("║  Auth       : set CONNECTOR_API_KEY env var      ║");
    println!("║  Docs       : http://{}:{}/docs           ║", host, port);
    println!("║  Health     : http://{}:{}/healthz        ║", host, port);
    println!("║  Ready      : http://{}:{}/readyz         ║", host, port);
    println!("║  Metrics    : http://{}:{}/metrics        ║", host, port);
    println!("╚══════════════════════════════════════════════════╝");
    println!();

    if dev_mode {
        println!("  ⚠  CONNECTOR_DEV_MODE is set — all auth checks bypassed!");
        println!("     Do not use in production.\n");
    }
    println!("  Press Ctrl-C to stop.\n");
}

fn pad_right(s: &str, n: usize) -> String {
    format!("{:<width$}", s, width = n)
}

fn truncate(s: &str, n: usize) -> String {
    if s.len() <= n {
        pad_right(s, n)
    } else {
        format!("{}…", &s[..n.saturating_sub(1)])
    }
}

/// Extract a simple `key = "value"` from raw TOML text (no full parser needed).
fn extract_toml_value<'a>(toml: &'a str, key: &str) -> Option<&'a str> {
    for line in toml.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(key) && trimmed.contains('=') {
            let val = trimmed.splitn(2, '=').nth(1)?.trim();
            return Some(val.trim_matches('"'));
        }
    }
    None
}

// ── path helpers ──────────────────────────────────────────────────────────────

fn expand_home(path: &str) -> PathBuf {
    if path.starts_with("~/") {
        let home = std::env::var("HOME")
            .or_else(|_| std::env::var("USERPROFILE"))
            .unwrap_or_else(|_| ".".to_string());
        PathBuf::from(home).join(&path[2..])
    } else {
        PathBuf::from(path)
    }
}
