#!/usr/bin/env bash
#
# Connector Platform Quickstart
# Single-command installation and setup
#
# Usage:
#   curl -fsSL https://connector.ai/install.sh | bash
#   # or
#   ./quickstart.sh [options]
#
# Options:
#   --dev           Development mode (no auth required)
#   --docker        Use Docker Compose
#   --k8s           Install to Kubernetes
#   --with-demo     Include demo agents
#   --port PORT     HTTP port (default: 9091)
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Defaults
MODE="binary"
DEV_MODE=false
WITH_DEMO=false
PORT=9091
DATA_DIR="${HOME}/.connector"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dev)
            DEV_MODE=true
            shift
            ;;
        --docker)
            MODE="docker"
            shift
            ;;
        --k8s)
            MODE="k8s"
            shift
            ;;
        --with-demo)
            WITH_DEMO=true
            shift
            ;;
        --port)
            PORT="$2"
            shift 2
            ;;
        --data-dir)
            DATA_DIR="$2"
            shift 2
            ;;
        -h|--help)
            echo "Connector Platform Quickstart"
            echo ""
            echo "Usage: $0 [options]"
            echo ""
            echo "Options:"
            echo "  --dev           Development mode (no auth required)"
            echo "  --docker        Use Docker Compose"
            echo "  --k8s           Install to Kubernetes"
            echo "  --with-demo     Include demo agents"
            echo "  --port PORT     HTTP port (default: 9091)"
            echo "  --data-dir DIR  Data directory (default: ~/.connector)"
            echo ""
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            exit 1
            ;;
    esac
done

# Banner
echo -e "${BLUE}"
cat << 'EOF'
   ____                            _             
  / ___|___  _ __  _ __   ___  ___| |_ ___  _ __ 
 | |   / _ \| '_ \| '_ \ / _ \/ __| __/ _ \| '__|
 | |__| (_) | | | | | | |  __/ (__| || (_) | |   
  \____\___/|_| |_|_| |_|\___|\___|\__\___/|_|   
                                                  
  Enterprise AI Agent Operating System
EOF
echo -e "${NC}"

echo -e "${GREEN}Starting Connector Platform quickstart...${NC}"
echo ""

# Detect OS
detect_os() {
    case "$(uname -s)" in
        Linux*)     OS=linux;;
        Darwin*)    OS=darwin;;
        CYGWIN*|MINGW*|MSYS*) OS=windows;;
        *)          OS=unknown;;
    esac
    
    case "$(uname -m)" in
        x86_64|amd64)   ARCH=amd64;;
        arm64|aarch64)  ARCH=arm64;;
        *)              ARCH=unknown;;
    esac
    
    echo -e "Detected: ${BLUE}${OS}/${ARCH}${NC}"
}

# Check prerequisites
check_prerequisites() {
    echo -e "\n${YELLOW}Checking prerequisites...${NC}"
    
    local missing=()
    
    if [[ "$MODE" == "docker" ]]; then
        command -v docker >/dev/null 2>&1 || missing+=("docker")
        command -v docker-compose >/dev/null 2>&1 || command -v "docker compose" >/dev/null 2>&1 || missing+=("docker-compose")
    elif [[ "$MODE" == "k8s" ]]; then
        command -v kubectl >/dev/null 2>&1 || missing+=("kubectl")
        command -v helm >/dev/null 2>&1 || missing+=("helm")
    else
        command -v curl >/dev/null 2>&1 || missing+=("curl")
    fi
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        echo -e "${RED}Missing prerequisites: ${missing[*]}${NC}"
        echo "Please install them and try again."
        exit 1
    fi
    
    echo -e "${GREEN}✓ All prerequisites met${NC}"
}

# Create data directory
setup_data_dir() {
    echo -e "\n${YELLOW}Setting up data directory...${NC}"
    mkdir -p "${DATA_DIR}"/{data,logs,config}
    echo -e "${GREEN}✓ Created ${DATA_DIR}${NC}"
}

# Generate configuration
generate_config() {
    echo -e "\n${YELLOW}Generating configuration...${NC}"
    
    local config_file="${DATA_DIR}/config/connector.toml"
    
    if [[ -f "$config_file" ]]; then
        echo -e "${YELLOW}Config exists, skipping...${NC}"
        return
    fi
    
    cat > "$config_file" << EOF
# Connector Platform Configuration
# Generated by quickstart.sh

[server]
host = "0.0.0.0"
port = ${PORT}
data_dir = "${DATA_DIR}/data"

[auth]
# Set to false in production
dev_mode = ${DEV_MODE}

[logging]
level = "info"
format = "json"
file = "${DATA_DIR}/logs/connector.log"

[kernel]
# Memory limits
max_packets = 100000
max_agents = 1000

[compliance]
# Enable for healthcare
hipaa_mode = false
# Enable for EU
gdpr_mode = false

[observability]
# Prometheus metrics
metrics_enabled = true
metrics_port = 9090

# OpenTelemetry
otel_enabled = false
# otel_endpoint = "http://localhost:4317"
EOF

    echo -e "${GREEN}✓ Generated ${config_file}${NC}"
}

# Docker Compose installation
install_docker() {
    echo -e "\n${YELLOW}Setting up Docker Compose...${NC}"
    
    local compose_file="${DATA_DIR}/docker-compose.yml"
    
    cat > "$compose_file" << EOF
version: '3.8'

services:
  connector:
    image: ghcr.io/connector-ai/connector-platform:latest
    container_name: connector
    ports:
      - "${PORT}:9091"
      - "9090:9090"
    volumes:
      - ${DATA_DIR}/data:/data
      - ${DATA_DIR}/config:/config
      - ${DATA_DIR}/logs:/logs
    environment:
      - CONNECTOR_CONFIG=/config/connector.toml
      - CONNECTOR_PORT=${PORT}
      - CONNECTOR_UI_DIR=/ui/dist
      - CONNECTOR_DEV_MODE=${DEV_MODE}
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "/usr/local/bin/connector-platform", "--health-check"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: connector-prometheus
    ports:
      - "9092:9090"
    volumes:
      - ${DATA_DIR}/prometheus.yml:/etc/prometheus/prometheus.yml
    profiles:
      - monitoring

  # Optional: Grafana for dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: connector-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    profiles:
      - monitoring
EOF

    # Create Prometheus config
    cat > "${DATA_DIR}/prometheus.yml" << EOF
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'connector'
    static_configs:
      - targets: ['connector:9091']
EOF

    echo -e "${GREEN}✓ Created ${compose_file}${NC}"
    
    # Start services
    echo -e "\n${YELLOW}Starting Connector...${NC}"
    cd "${DATA_DIR}"
    docker-compose up -d
    
    echo -e "${GREEN}✓ Connector is starting...${NC}"
}

# Kubernetes installation
install_k8s() {
    echo -e "\n${YELLOW}Installing to Kubernetes...${NC}"
    
    # Check if namespace exists
    if ! kubectl get namespace connector >/dev/null 2>&1; then
        kubectl create namespace connector
    fi
    
    # Add Helm repo (if hosted)
    # helm repo add connector https://charts.connector.ai
    # helm repo update
    
    # Install using local chart
    local chart_path="${DATA_DIR}/helm/connector"
    
    if [[ ! -d "$chart_path" ]]; then
        echo -e "${YELLOW}Downloading Helm chart...${NC}"
        mkdir -p "${DATA_DIR}/helm"
        # In production, this would download from a chart repo
        # For now, we'll create a minimal values file
        cat > "${DATA_DIR}/helm-values.yaml" << EOF
replicaCount: 1

image:
  repository: ghcr.io/connector-ai/connector-platform
  tag: latest

service:
  type: ClusterIP
  port: 9091

env:
  CONNECTOR_PORT: "${PORT}"
  CONNECTOR_DEV_MODE: "${DEV_MODE}"

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"
EOF
    fi
    
    echo -e "${GREEN}✓ Helm values created at ${DATA_DIR}/helm-values.yaml${NC}"
    echo ""
    echo "To install, run:"
    echo "  helm install connector ./platform/deploy/helm/connector -f ${DATA_DIR}/helm-values.yaml -n connector"
}

# Binary installation
install_binary() {
    echo -e "\n${YELLOW}Installing Connector binary...${NC}"
    
    local bin_dir="${HOME}/.local/bin"
    mkdir -p "$bin_dir"
    
    # Download URL (placeholder - would be real in production)
    local download_url="https://github.com/connector-ai/connector/releases/latest/download/connector-${OS}-${ARCH}"
    
    echo -e "${YELLOW}Note: Binary download not yet available.${NC}"
    echo "For now, build from source:"
    echo ""
    echo "  git clone https://github.com/connector-ai/connector.git"
    echo "  cd connector/platform/server"
    echo "  cargo build --release"
    echo "  cp target/release/connector-platform ${bin_dir}/connector-platform"
    echo "  cp target/release/connectorctl ${bin_dir}/connectorctl"
    echo ""
    
    # Check if running from source
    local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local server_dir="${script_dir}/../server"
    
    if [[ -f "${server_dir}/Cargo.toml" ]]; then
        echo -e "${YELLOW}Detected source directory. Building...${NC}"
        cd "$server_dir"
        cargo build --release
        
        local binary="${server_dir}/target/release/connector-platform"
        local ctl_binary="${server_dir}/target/release/connectorctl"
        if [[ -f "$binary" ]]; then
            cp "$binary" "${bin_dir}/connector-platform"
            chmod +x "${bin_dir}/connector-platform"
            echo -e "${GREEN}✓ Installed to ${bin_dir}/connector-platform${NC}"
        fi
        if [[ -f "$ctl_binary" ]]; then
            cp "$ctl_binary" "${bin_dir}/connectorctl"
            chmod +x "${bin_dir}/connectorctl"
            echo -e "${GREEN}✓ Installed to ${bin_dir}/connectorctl${NC}"
        fi
    fi
}

# Create demo agents
create_demo_agents() {
    if [[ "$WITH_DEMO" != "true" ]]; then
        return
    fi
    
    echo -e "\n${YELLOW}Creating demo agents...${NC}"
    
    local api_url="http://localhost:${PORT}/api/v2"
    
    # Wait for server to be ready
    echo "Waiting for server..."
    for i in {1..30}; do
        if curl -s "${api_url}/health" >/dev/null 2>&1; then
            break
        fi
        sleep 1
    done
    
    # Create demo agent
    curl -s -X POST "${api_url}/agents" \
        -H "Content-Type: application/json" \
        -d '{"name": "demo-agent", "description": "Demo agent for quickstart"}' \
        >/dev/null 2>&1 || true
    
    echo -e "${GREEN}✓ Demo agents created${NC}"
}

# Print success message
print_success() {
    echo ""
    echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}  Connector Platform is ready!${NC}"
    echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo -e "  ${BLUE}Dashboard:${NC}  http://localhost:${PORT}/"
    echo -e "  ${BLUE}API:${NC}        http://localhost:${PORT}"
    echo -e "  ${BLUE}Health:${NC}     http://localhost:${PORT}/health"
    echo -e "  ${BLUE}Metrics:${NC}    http://localhost:${PORT}/metrics"
    echo -e "  ${BLUE}Data:${NC}       ${DATA_DIR}"
    echo ""
    echo -e "  ${YELLOW}Connector OS:${NC}"
    echo "    connectorctl version"
    echo "    connectorctl help"
    echo "    connectorctl start"
    echo "    connectorctl status"
    echo ""
    echo -e "  ${YELLOW}Quick commands:${NC}"
    echo "    # Create an agent"
    echo "    curl -X POST http://localhost:${PORT}/api/v2/agents \\"
    echo "      -H 'Content-Type: application/json' \\"
    echo "      -d '{\"name\": \"my-agent\"}'"
    echo ""
    echo "    # Write memory"
    echo "    curl -X POST http://localhost:${PORT}/api/v2/memory \\"
    echo "      -H 'Content-Type: application/json' \\"
    echo "      -d '{\"agent_id\": \"my-agent\", \"content\": {\"hello\": \"world\"}}'"
    echo ""
    echo "    # Get audit log (OCSF format)"
    echo "    curl 'http://localhost:${PORT}/api/v2/audit?format=ocsf'"
    echo ""
    echo -e "  ${YELLOW}Documentation:${NC}"
    echo "    https://connector.ai/docs"
    echo ""
    
    if [[ "$DEV_MODE" == "true" ]]; then
        echo -e "  ${YELLOW}⚠️  Running in DEV MODE - no authentication required${NC}"
        echo ""
    fi
}

# Main
main() {
    detect_os
    check_prerequisites
    setup_data_dir
    generate_config
    
    case "$MODE" in
        docker)
            install_docker
            ;;
        k8s)
            install_k8s
            ;;
        binary)
            install_binary
            ;;
    esac
    
    create_demo_agents
    print_success
}

main
